version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./src/backend:/app
    command: npm run start:dev

volumes:
  mongo_data:
